---
- hosts: all
  connection: local
  tasks:
  - name: create user admin
    fortios_system_admin:
     system_admin:
       host: 172.22.117.46
       username: Ansible
       accprofile: super_admin
       accprofile_override: disable
       allow_remove_admin_session: enable
       comments: usuario 1 admin
       email_to: omar.robayog.ext@claro.com.co
       force_password_change: enable
       fortitoken: disable
       guest_auth: disable
       name: admin4
       password:
       remote_auth: enable
       remote_group: TACACS+

